# --- BASE ---
baseURL = "https://ivanprestini.com/"
title = "Prestini Consulting"
theme = "github.com/devcows/hugo-universal-theme"

# --- LINGUE ---
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true   # crea /it/, /es/, /en/ (utile per test e SEO)

# --- NAVBAR ---
[params]
  disabled_logo = true
  logo_text = "Prestini Consulting"

[languages]
  [languages.it]
    languageName = "Italiano"
    weight = 1

  [languages.es]
    languageName = "Espa√±ol"
    weight = 2

  [languages.en]
    languageName = "English"
    weight = 3

[[menu.main]]
  name = "Bio"
  url = "#bio"
  weight = 20
