# --- BASE ---
baseURL = "https://ivanprestini.com/"
title = "Prestini Consulting"
theme = "github.com/devcows/hugo-universal-theme"

# --- LINGUE ---
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true   # crea /it/, /es/, /en/ (utile per test e SEO)

# --- NAVBAR ---
[params]
  disabled_logo = true
  logo_text = "Prestini Consulting"

[languages]
  [languages.it]
    languageName = "Italiano"
    weight = 1

  [languages.es]
    languageName = "Español"
    weight = 2

  [languages.en]
    languageName = "English"
    weight = 3

[[menu.main]]
  name = "Bio"
  url = "#bio"
  weight = 20

[params.clients]
enable   = true
title    = "Our Partners"
subtitle = "We have proudly collaborated with the following companies."

[params.CarouselCustomers]
items = 5
auto_play = true          # <— questo abilita l’autoplay dai data-attributes
slide_speed = 400
pagination_speed = 600