# --- BASE ---
baseURL = "https://ivanprestini.com/"
title = "Prestini Consulting"
theme = "github.com/devcows/hugo-universal-theme"

# --- LINGUE ---
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true   # crea /it/, /es/, /en/ (utile per test e SEO)

  # --- NAVBAR ---
[params]
  disabled_logo = true
  logo_text = "Prestini Consulting"

[languages]
  [languages.it]
    languageName = "Italiano"
    weight = 1

  [languages.es]
    languageName = "Español"
    weight = 2

  [languages.en]
    languageName = "English"
    weight = 3

[[menu.main]]
  name = "Bio"
  url = "#bio"
  weight = 20

# --- FORNITORI ---
[params.clients]
enable   = true

[params.CarouselCustomers]
items = 5
auto_play = true          # <— questo abilita l’autoplay dai data-attributes
slide_speed = 400
pagination_speed = 600

  # --- CREDITS ---
[params.testimonials]
enable   = true

[params.CarouselTestimonials]
items = 3
auto_play = true
slide_speed = 800
pagination_speed = 600

  # --- SEE MORE ---
[params.see_more]
enable   = true
title   = "Un claim molto catchy"
subtitle  = "Fuffa qua e la può solo far bene. Non necessariamente verrà letta ma qualcosa mi dice che darà al tutto un aspetto professionale e accattivante."
link_url  = "github.com/devcows/hugo-universal-theme"
link_text = "TASTO MOLTO UTILE"
icon  = "fas fa-globe"

  # --- FEATURES ---
[params.features]
enable   = true
cols     = 3         # numero di colonne nella griglia (se previsto)